name: read time sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_PAGE: ${{ secrets.NOTION_PAGE }}
      WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
      CC_URL: ${{ secrets.CC_URL }}
      CC_ID: ${{ secrets.CC_ID }}
      CC_PASSWORD: ${{ secrets.CC_PASSWORD }}
      HEATMAP_BLOCK_ID: ${{ secrets.HEATMAP_BLOCK_ID }}
      BOOK_DATABASE_NAME: ${{ vars.BOOK_DATABASE_NAME }}
      AUTHOR_DATABASE_NAME: ${{ vars.AUTHOR_DATABASE_NAME }}
      CATEGORY_DATABASE_NAME: ${{ vars.CATEGORY_DATABASE_NAME }}
      BOOKMARK_DATABASE_NAME: ${{ vars.BOOKMARK_DATABASE_NAME }}
      REVIEW_DATABASE_NAME: ${{ vars.REVIEW_DATABASE_NAME }}
      CHAPTER_DATABASE_NAME: ${{ vars.CHAPTER_DATABASE_NAME }}
      YEAR_DATABASE_NAME: ${{ vars.YEAR_DATABASE_NAME }}
      WEEK_DATABASE_NAME: ${{ vars.WEEK_DATABASE_NAME }}
      MONTH_DATABASE_NAME: ${{ vars.MONTH_DATABASE_NAME }}
      DAY_DATABASE_NAME: ${{ vars.DAY_DATABASE_NAME }}
      REF: ${{ github.ref }}
      REPOSITORY: ${{ github.repository }}
      YEAR: ${{ vars.YEAR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Remove folder
        run: rm -rf ./OUT_FOLDER
      - name: Set default year if not provided
        run: echo "YEAR=$(date +"%Y")" >> $GITHUB_ENV
        if: env.YEAR == ''
      - name: Set default colors
        run: |
          # 设置默认颜色，如果没有在 vars 中定义则使用默认值
          BG_COLOR="${{ vars.background_color }}"
          [[ -z "$BG_COLOR" ]] && BG_COLOR="#FFFFFF"
          TRACK_COLOR="${{ vars.track_color }}"
          [[ -z "$TRACK_COLOR" ]] && TRACK_COLOR="#ACE7AE"
          SPECIAL_COLOR="${{ vars.special_color }}"
          [[ -z "$SPECIAL_COLOR" ]] && SPECIAL_COLOR="#69C16E"
          SPECIAL_COLOR2="${{ vars.special_color2 }}"
          [[ -z "$SPECIAL_COLOR2" ]] && SPECIAL_COLOR2="#549F57"
          DOM_COLOR="${{ vars.dom_color }}"
          [[ -z "$DOM_COLOR" ]] && DOM_COLOR="#EBEDF0"
          TEXT_COLOR="${{ vars.text_color }}"
          [[ -z "$TEXT_COLOR" ]] && TEXT_COLOR="#000000"
          
          echo "BG_COLOR=$BG_COLOR" >> $GITHUB_ENV
          echo "TRACK_COLOR=$TRACK_COLOR" >> $GITHUB_ENV
          echo "SPECIAL_COLOR=$SPECIAL_COLOR" >> $GITHUB_ENV
          echo "SPECIAL_COLOR2=$SPECIAL_COLOR2" >> $GITHUB_ENV
          echo "DOM_COLOR=$DOM_COLOR" >> $GITHUB_ENV
          echo "TEXT_COLOR=$TEXT_COLOR" >> $GITHUB_ENV
      - name: weread heatmap
        run: |
          github_heatmap weread --year $YEAR  --me "${{secrets.NAME}}" --with-animation --background-color=$BG_COLOR --track-color=$TRACK_COLOR --special-color1=$SPECIAL_COLOR --special-color2=$SPECIAL_COLOR2 --dom-color=$DOM_COLOR --text-color=$TEXT_COLOR
      - name: push
        run: |		
            git checkout --orphan output		
            git reset		
            git config --local user.email "action@github.com"		
            git config --local user.name "GitHub Action"		
            git add ./OUT_FOLDER		
            git commit -m '生成热力图' || echo "nothing to commit"		
            git push origin output -f || echo "nothing to push"
      - name: read time sync
        run: |
          read_time
      
